#[cfg(any(feature = "atmega48p", feature = "atmega168", feature = "atmega328p"))]
avr_hal_generic::impl_port_traditional! {
    enum Ports {
        PORTB: (crate::pac::PORTB, portb, pinb, ddrb),
        PORTC: (crate::pac::PORTC, portc, pinc, ddrc),
        PORTD: (crate::pac::PORTD, portd, pind, ddrd),
    }

    pub struct Pins {
        pb0: PB0 = (crate::pac::PORTB, PORTB, 0, portb, pinb, ddrb),
        pb1: PB1 = (crate::pac::PORTB, PORTB, 1, portb, pinb, ddrb),
        pb2: PB2 = (crate::pac::PORTB, PORTB, 2, portb, pinb, ddrb),
        pb3: PB3 = (crate::pac::PORTB, PORTB, 3, portb, pinb, ddrb),
        pb4: PB4 = (crate::pac::PORTB, PORTB, 4, portb, pinb, ddrb),
        pb5: PB5 = (crate::pac::PORTB, PORTB, 5, portb, pinb, ddrb),
        pb6: PB6 = (crate::pac::PORTB, PORTB, 6, portb, pinb, ddrb),
        pb7: PB7 = (crate::pac::PORTB, PORTB, 7, portb, pinb, ddrb),
        pc0: PC0 = (crate::pac::PORTC, PORTC, 0, portc, pinc, ddrc),
        pc1: PC1 = (crate::pac::PORTC, PORTC, 1, portc, pinc, ddrc),
        pc2: PC2 = (crate::pac::PORTC, PORTC, 2, portc, pinc, ddrc),
        pc3: PC3 = (crate::pac::PORTC, PORTC, 3, portc, pinc, ddrc),
        pc4: PC4 = (crate::pac::PORTC, PORTC, 4, portc, pinc, ddrc),
        pc5: PC5 = (crate::pac::PORTC, PORTC, 5, portc, pinc, ddrc),
        pc6: PC6 = (crate::pac::PORTC, PORTC, 6, portc, pinc, ddrc),
        pd0: PD0 = (crate::pac::PORTD, PORTD, 0, portd, pind, ddrd),
        pd1: PD1 = (crate::pac::PORTD, PORTD, 1, portd, pind, ddrd),
        pd2: PD2 = (crate::pac::PORTD, PORTD, 2, portd, pind, ddrd),
        pd3: PD3 = (crate::pac::PORTD, PORTD, 3, portd, pind, ddrd),
        pd4: PD4 = (crate::pac::PORTD, PORTD, 4, portd, pind, ddrd),
        pd5: PD5 = (crate::pac::PORTD, PORTD, 5, portd, pind, ddrd),
        pd6: PD6 = (crate::pac::PORTD, PORTD, 6, portd, pind, ddrd),
        pd7: PD7 = (crate::pac::PORTD, PORTD, 7, portd, pind, ddrd),
    }
}

#[cfg(feature = "atmega328pb")]
avr_hal_generic::impl_port_traditional! {
    enum Ports {
        PORTB: (crate::pac::PORTB, portb, pinb, ddrb),
        PORTC: (crate::pac::PORTC, portc, pinc, ddrc),
        PORTD: (crate::pac::PORTD, portd, pind, ddrd),
        PORTE: (crate::pac::PORTE, porte, pine, ddre),
    }

    pub struct Pins {
        pb0: PB0 = (crate::pac::PORTB, PORTB, 0, portb, pinb, ddrb),
        pb1: PB1 = (crate::pac::PORTB, PORTB, 1, portb, pinb, ddrb),
        pb2: PB2 = (crate::pac::PORTB, PORTB, 2, portb, pinb, ddrb),
        pb3: PB3 = (crate::pac::PORTB, PORTB, 3, portb, pinb, ddrb),
        pb4: PB4 = (crate::pac::PORTB, PORTB, 4, portb, pinb, ddrb),
        pb5: PB5 = (crate::pac::PORTB, PORTB, 5, portb, pinb, ddrb),
        pb6: PB6 = (crate::pac::PORTB, PORTB, 6, portb, pinb, ddrb),
        pb7: PB7 = (crate::pac::PORTB, PORTB, 7, portb, pinb, ddrb),
        pc0: PC0 = (crate::pac::PORTC, PORTC, 0, portc, pinc, ddrc),
        pc1: PC1 = (crate::pac::PORTC, PORTC, 1, portc, pinc, ddrc),
        pc2: PC2 = (crate::pac::PORTC, PORTC, 2, portc, pinc, ddrc),
        pc3: PC3 = (crate::pac::PORTC, PORTC, 3, portc, pinc, ddrc),
        pc4: PC4 = (crate::pac::PORTC, PORTC, 4, portc, pinc, ddrc),
        pc5: PC5 = (crate::pac::PORTC, PORTC, 5, portc, pinc, ddrc),
        pc6: PC6 = (crate::pac::PORTC, PORTC, 6, portc, pinc, ddrc),
        pd0: PD0 = (crate::pac::PORTD, PORTD, 0, portd, pind, ddrd),
        pd1: PD1 = (crate::pac::PORTD, PORTD, 1, portd, pind, ddrd),
        pd2: PD2 = (crate::pac::PORTD, PORTD, 2, portd, pind, ddrd),
        pd3: PD3 = (crate::pac::PORTD, PORTD, 3, portd, pind, ddrd),
        pd4: PD4 = (crate::pac::PORTD, PORTD, 4, portd, pind, ddrd),
        pd5: PD5 = (crate::pac::PORTD, PORTD, 5, portd, pind, ddrd),
        pd6: PD6 = (crate::pac::PORTD, PORTD, 6, portd, pind, ddrd),
        pd7: PD7 = (crate::pac::PORTD, PORTD, 7, portd, pind, ddrd),
        pe0: PE0 = (crate::pac::PORTE, PORTE, 0, porte, pine, ddre),
        pe1: PE1 = (crate::pac::PORTE, PORTE, 1, porte, pine, ddre),
        pe2: PE2 = (crate::pac::PORTE, PORTE, 2, porte, pine, ddre),
        pe3: PE3 = (crate::pac::PORTE, PORTE, 3, porte, pine, ddre),
    }
}

#[cfg(feature = "atmega32u4")]
avr_hal_generic::impl_port_traditional! {
    enum Ports {
        PORTB: (crate::pac::PORTB, portb, pinb, ddrb),
        PORTC: (crate::pac::PORTC, portc, pinc, ddrc),
        PORTD: (crate::pac::PORTD, portd, pind, ddrd),
        PORTE: (crate::pac::PORTE, porte, pine, ddre),
        PORTF: (crate::pac::PORTF, portf, pinf, ddrf),
    }

    pub struct Pins {
        pb0: PB0 = (crate::pac::PORTB, PORTB, 0, portb, pinb, ddrb),
        pb1: PB1 = (crate::pac::PORTB, PORTB, 1, portb, pinb, ddrb),
        pb2: PB2 = (crate::pac::PORTB, PORTB, 2, portb, pinb, ddrb),
        pb3: PB3 = (crate::pac::PORTB, PORTB, 3, portb, pinb, ddrb),
        pb4: PB4 = (crate::pac::PORTB, PORTB, 4, portb, pinb, ddrb),
        pb5: PB5 = (crate::pac::PORTB, PORTB, 5, portb, pinb, ddrb),
        pb6: PB6 = (crate::pac::PORTB, PORTB, 6, portb, pinb, ddrb),
        pb7: PB7 = (crate::pac::PORTB, PORTB, 7, portb, pinb, ddrb),
        pc6: PC6 = (crate::pac::PORTC, PORTC, 6, portc, pinc, ddrc),
        pc7: PC7 = (crate::pac::PORTC, PORTC, 7, portc, pinc, ddrc),
        pd0: PD0 = (crate::pac::PORTD, PORTD, 0, portd, pind, ddrd),
        pd1: PD1 = (crate::pac::PORTD, PORTD, 1, portd, pind, ddrd),
        pd2: PD2 = (crate::pac::PORTD, PORTD, 2, portd, pind, ddrd),
        pd3: PD3 = (crate::pac::PORTD, PORTD, 3, portd, pind, ddrd),
        pd4: PD4 = (crate::pac::PORTD, PORTD, 4, portd, pind, ddrd),
        pd5: PD5 = (crate::pac::PORTD, PORTD, 5, portd, pind, ddrd),
        pd6: PD6 = (crate::pac::PORTD, PORTD, 6, portd, pind, ddrd),
        pd7: PD7 = (crate::pac::PORTD, PORTD, 7, portd, pind, ddrd),
        pe2: PE2 = (crate::pac::PORTE, PORTE, 2, porte, pine, ddre),
        pe6: PE6 = (crate::pac::PORTE, PORTE, 6, porte, pine, ddre),
        pf0: PF0 = (crate::pac::PORTF, PORTF, 0, portf, pinf, ddrf),
        pf1: PF1 = (crate::pac::PORTF, PORTF, 1, portf, pinf, ddrf),
        pf4: PF4 = (crate::pac::PORTF, PORTF, 4, portf, pinf, ddrf),
        pf5: PF5 = (crate::pac::PORTF, PORTF, 5, portf, pinf, ddrf),
        pf6: PF6 = (crate::pac::PORTF, PORTF, 6, portf, pinf, ddrf),
        pf7: PF7 = (crate::pac::PORTF, PORTF, 7, portf, pinf, ddrf),
    }
}

#[cfg(any(feature = "atmega1280", feature = "atmega2560"))]
avr_hal_generic::impl_port_traditional! {
    enum ports {
        porta: (crate::pac::porta, porta, pina, ddra),
        portb: (crate::pac::portb, portb, pinb, ddrb),
        portc: (crate::pac::portc, portc, pinc, ddrc),
        portd: (crate::pac::portd, portd, pind, ddrd),
        porte: (crate::pac::porte, porte, pine, ddre),
        portf: (crate::pac::portf, portf, pinf, ddrf),
        portg: (crate::pac::portg, portg, ping, ddrg),
        porth: (crate::pac::porth, porth, pinh, ddrh),
        portj: (crate::pac::portj, portj, pinj, ddrj),
        portk: (crate::pac::portk, portk, pink, ddrk),
        portl: (crate::pac::portl, portl, pinl, ddrl),
    }

    pub struct pins {
        pa0: pa0 = (crate::pac::porta, porta, 0, porta, pina, ddra),
        pa1: pa1 = (crate::pac::porta, porta, 1, porta, pina, ddra),
        pa2: pa2 = (crate::pac::porta, porta, 2, porta, pina, ddra),
        pa3: pa3 = (crate::pac::porta, porta, 3, porta, pina, ddra),
        pa4: pa4 = (crate::pac::porta, porta, 4, porta, pina, ddra),
        pa5: pa5 = (crate::pac::porta, porta, 5, porta, pina, ddra),
        pa6: pa6 = (crate::pac::porta, porta, 6, porta, pina, ddra),
        pa7: pa7 = (crate::pac::porta, porta, 7, porta, pina, ddra),
        pb0: pb0 = (crate::pac::portb, portb, 0, portb, pinb, ddrb),
        pb1: pb1 = (crate::pac::portb, portb, 1, portb, pinb, ddrb),
        pb2: pb2 = (crate::pac::portb, portb, 2, portb, pinb, ddrb),
        pb3: pb3 = (crate::pac::portb, portb, 3, portb, pinb, ddrb),
        pb4: pb4 = (crate::pac::portb, portb, 4, portb, pinb, ddrb),
        pb5: pb5 = (crate::pac::portb, portb, 5, portb, pinb, ddrb),
        pb6: pb6 = (crate::pac::portb, portb, 6, portb, pinb, ddrb),
        pb7: pb7 = (crate::pac::portb, portb, 7, portb, pinb, ddrb),
        pc0: pc0 = (crate::pac::portc, portc, 0, portc, pinc, ddrc),
        pc1: pc1 = (crate::pac::portc, portc, 1, portc, pinc, ddrc),
        pc2: pc2 = (crate::pac::portc, portc, 2, portc, pinc, ddrc),
        pc3: pc3 = (crate::pac::portc, portc, 3, portc, pinc, ddrc),
        pc4: pc4 = (crate::pac::portc, portc, 4, portc, pinc, ddrc),
        pc5: pc5 = (crate::pac::portc, portc, 5, portc, pinc, ddrc),
        pc6: pc6 = (crate::pac::portc, portc, 6, portc, pinc, ddrc),
        pc7: pc7 = (crate::pac::portc, portc, 7, portc, pinc, ddrc),
        pd0: pd0 = (crate::pac::portd, portd, 0, portd, pind, ddrd),
        pd1: pd1 = (crate::pac::portd, portd, 1, portd, pind, ddrd),
        pd2: pd2 = (crate::pac::portd, portd, 2, portd, pind, ddrd),
        pd3: pd3 = (crate::pac::portd, portd, 3, portd, pind, ddrd),
        pd4: pd4 = (crate::pac::portd, portd, 4, portd, pind, ddrd),
        pd5: pd5 = (crate::pac::portd, portd, 5, portd, pind, ddrd),
        pd6: pd6 = (crate::pac::portd, portd, 6, portd, pind, ddrd),
        pd7: pd7 = (crate::pac::portd, portd, 7, portd, pind, ddrd),
        pe0: pe0 = (crate::pac::porte, porte, 0, porte, pine, ddre),
        pe1: pe1 = (crate::pac::porte, porte, 1, porte, pine, ddre),
        pe2: pe2 = (crate::pac::porte, porte, 2, porte, pine, ddre),
        pe3: pe3 = (crate::pac::porte, porte, 3, porte, pine, ddre),
        pe4: pe4 = (crate::pac::porte, porte, 4, porte, pine, ddre),
        pe5: pe5 = (crate::pac::porte, porte, 5, porte, pine, ddre),
        pe6: pe6 = (crate::pac::porte, porte, 6, porte, pine, ddre),
        pe7: pe7 = (crate::pac::porte, porte, 7, porte, pine, ddre),
        pf0: pf0 = (crate::pac::portf, portf, 0, portf, pinf, ddrf),
        pf1: pf1 = (crate::pac::portf, portf, 1, portf, pinf, ddrf),
        pf2: pf2 = (crate::pac::portf, portf, 2, portf, pinf, ddrf),
        pf3: pf3 = (crate::pac::portf, portf, 3, portf, pinf, ddrf),
        pf4: pf4 = (crate::pac::portf, portf, 4, portf, pinf, ddrf),
        pf5: pf5 = (crate::pac::portf, portf, 5, portf, pinf, ddrf),
        pf6: pf6 = (crate::pac::portf, portf, 6, portf, pinf, ddrf),
        pf7: pf7 = (crate::pac::portf, portf, 7, portf, pinf, ddrf),
        pg0: pg0 = (crate::pac::portg, portg, 0, portg, ping, ddrg),
        pg1: pg1 = (crate::pac::portg, portg, 1, portg, ping, ddrg),
        pg2: pg2 = (crate::pac::portg, portg, 2, portg, ping, ddrg),
        pg3: pg3 = (crate::pac::portg, portg, 3, portg, ping, ddrg),
        pg4: pg4 = (crate::pac::portg, portg, 4, portg, ping, ddrg),
        pg5: pg5 = (crate::pac::portg, portg, 5, portg, ping, ddrg),
        ph0: ph0 = (crate::pac::porth, porth, 0, porth, pinh, ddrh),
        ph1: ph1 = (crate::pac::porth, porth, 1, porth, pinh, ddrh),
        ph2: ph2 = (crate::pac::porth, porth, 2, porth, pinh, ddrh),
        ph3: ph3 = (crate::pac::porth, porth, 3, porth, pinh, ddrh),
        ph4: ph4 = (crate::pac::porth, porth, 4, porth, pinh, ddrh),
        ph5: ph5 = (crate::pac::porth, porth, 5, porth, pinh, ddrh),
        ph6: ph6 = (crate::pac::porth, porth, 6, porth, pinh, ddrh),
        ph7: ph7 = (crate::pac::porth, porth, 7, porth, pinh, ddrh),
        pj0: pj0 = (crate::pac::portj, portj, 0, portj, pinj, ddrj),
        pj1: pj1 = (crate::pac::portj, portj, 1, portj, pinj, ddrj),
        pj2: pj2 = (crate::pac::portj, portj, 2, portj, pinj, ddrj),
        pj3: pj3 = (crate::pac::portj, portj, 3, portj, pinj, ddrj),
        pj4: pj4 = (crate::pac::portj, portj, 4, portj, pinj, ddrj),
        pj5: pj5 = (crate::pac::portj, portj, 5, portj, pinj, ddrj),
        pj6: pj6 = (crate::pac::portj, portj, 6, portj, pinj, ddrj),
        pj7: pj7 = (crate::pac::portj, portj, 7, portj, pinj, ddrj),
        pk0: pk0 = (crate::pac::portk, portk, 0, portk, pink, ddrk),
        pk1: pk1 = (crate::pac::portk, portk, 1, portk, pink, ddrk),
        pk2: pk2 = (crate::pac::portk, portk, 2, portk, pink, ddrk),
        pk3: pk3 = (crate::pac::portk, portk, 3, portk, pink, ddrk),
        pk4: pk4 = (crate::pac::portk, portk, 4, portk, pink, ddrk),
        pk5: pk5 = (crate::pac::portk, portk, 5, portk, pink, ddrk),
        pk6: pk6 = (crate::pac::portk, portk, 6, portk, pink, ddrk),
        pk7: pk7 = (crate::pac::portk, portk, 7, portk, pink, ddrk),
        pl0: pl0 = (crate::pac::portl, portl, 0, portl, pinl, ddrl),
        pl1: pl1 = (crate::pac::portl, portl, 1, portl, pinl, ddrl),
        pl2: pl2 = (crate::pac::portl, portl, 2, portl, pinl, ddrl),
        pl3: pl3 = (crate::pac::portl, portl, 3, portl, pinl, ddrl),
        pl4: pl4 = (crate::pac::portl, portl, 4, portl, pinl, ddrl),
        pl5: pl5 = (crate::pac::portl, portl, 5, portl, pinl, ddrl),
        pl6: pl6 = (crate::pac::portl, portl, 6, portl, pinl, ddrl),
        pl7: pl7 = (crate::pac::portl, portl, 7, portl, pinl, ddrl),
    }
}

#[cfg(feature="atmega128rfa1")]
avr_hal_generic::impl_port_traditional! {
    enum Ports {
		PORTA: (crate::pac::PORTA, porta, pina, ddra),
        PORTB: (crate::pac::PORTB, portb, pinb, ddrb),
		PORTC: (crate::pac::PORTC, portc, pinc, ddrc),
        PORTD: (crate::pac::PORTD, portd, pind, ddrd),
        PORTE: (crate::pac::PORTE, porte, pine, ddre),
        PORTF: (crate::pac::PORTF, portf, pinf, ddrf),
        PORTG: (crate::pac::PORTG, portg, ping, ddrg),
    }

    pub struct Pins {
        pa0: PA0 = (crate::pac::PORTA, PORTA, 0, porta, pina, ddra),
        pa1: PA1 = (crate::pac::PORTA, PORTA, 1, porta, pina, ddra),
        pa2: PA2 = (crate::pac::PORTA, PORTA, 2, porta, pina, ddra),
        pa3: PA3 = (crate::pac::PORTA, PORTA, 3, porta, pina, ddra),
        pa4: PA4 = (crate::pac::PORTA, PORTA, 4, porta, pina, ddra),
        pa5: PA5 = (crate::pac::PORTA, PORTA, 5, porta, pina, ddra),
        pa6: PA6 = (crate::pac::PORTA, PORTA, 6, porta, pina, ddra),
        pa7: PA7 = (crate::pac::PORTA, PORTA, 7, porta, pina, ddra),
        pb0: PB0 = (crate::pac::PORTB, PORTB, 0, portb, pinb, ddrb),
        pb1: PB1 = (crate::pac::PORTB, PORTB, 1, portb, pinb, ddrb),
        pb2: PB2 = (crate::pac::PORTB, PORTB, 2, portb, pinb, ddrb),
        pb3: PB3 = (crate::pac::PORTB, PORTB, 3, portb, pinb, ddrb),
        pb4: PB4 = (crate::pac::PORTB, PORTB, 4, portb, pinb, ddrb),
        pb5: PB5 = (crate::pac::PORTB, PORTB, 5, portb, pinb, ddrb),
        pb6: PB6 = (crate::pac::PORTB, PORTB, 6, portb, pinb, ddrb),
        pb7: PB7 = (crate::pac::PORTB, PORTB, 7, portb, pinb, ddrb),
        pc0: PC0 = (crate::pac::PORTC, PORTC, 1, portc, pinc, ddrc),
        pc1: PC1 = (crate::pac::PORTC, PORTC, 1, portc, pinc, ddrc),
        pc2: PC2 = (crate::pac::PORTC, PORTC, 2, portc, pinc, ddrc),
        pc3: PC3 = (crate::pac::PORTC, PORTC, 3, portc, pinc, ddrc),
        pc4: PC4 = (crate::pac::PORTC, PORTC, 4, portc, pinc, ddrc),
        pc5: PC5 = (crate::pac::PORTC, PORTC, 5, portc, pinc, ddrc),
        pc6: PC6 = (crate::pac::PORTC, PORTC, 6, portc, pinc, ddrc),
        pc7: PC7 = (crate::pac::PORTC, PORTC, 7, portc, pinc, ddrc),
        pd0: PD0 = (crate::pac::PORTD, PORTD, 0, portd, pind, ddrd),
        pd1: PD1 = (crate::pac::PORTD, PORTD, 1, portd, pind, ddrd),
        pd2: PD2 = (crate::pac::PORTD, PORTD, 2, portd, pind, ddrd),
        pd3: PD3 = (crate::pac::PORTD, PORTD, 3, portd, pind, ddrd),
        pd4: PD4 = (crate::pac::PORTD, PORTD, 4, portd, pind, ddrd),
        pd5: PD5 = (crate::pac::PORTD, PORTD, 5, portd, pind, ddrd),
        pd6: PD6 = (crate::pac::PORTD, PORTD, 6, portd, pind, ddrd),
        pd7: PD7 = (crate::pac::PORTD, PORTD, 7, portd, pind, ddrd),
        pe0: PE0 = (crate::pac::PORTE, PORTE, 0, porte, pine, ddre),
        pe1: PE1 = (crate::pac::PORTE, PORTE, 1, porte, pine, ddre),
        pe2: PE2 = (crate::pac::PORTE, PORTE, 2, porte, pine, ddre),
        pe3: PE3 = (crate::pac::PORTE, PORTE, 3, porte, pine, ddre),
        pe4: PE4 = (crate::pac::PORTE, PORTE, 4, porte, pine, ddre),
        pe5: PE5 = (crate::pac::PORTE, PORTE, 5, porte, pine, ddre),
        pe6: PE6 = (crate::pac::PORTE, PORTE, 6, porte, pine, ddre),
        pe7: PE7 = (crate::pac::PORTE, PORTE, 7, porte, pine, ddre),
        pf0: PF0 = (crate::pac::PORTF, PORTF, 0, portf, pinf, ddrf),
        pf1: PF1 = (crate::pac::PORTF, PORTF, 1, portf, pinf, ddrf),
        pf2: PF2 = (crate::pac::PORTF, PORTF, 2, portf, pinf, ddrf),
        pf3: PF3 = (crate::pac::PORTF, PORTF, 3, portf, pinf, ddrf),
        pf4: PF4 = (crate::pac::PORTF, PORTF, 4, portf, pinf, ddrf),
        pf5: PF5 = (crate::pac::PORTF, PORTF, 5, portf, pinf, ddrf),
        pf6: PF6 = (crate::pac::PORTF, PORTF, 6, portf, pinf, ddrf),
        pf7: PF7 = (crate::pac::PORTF, PORTF, 7, portf, pinf, ddrf),
        pg0: PG0 = (crate::pac::PORTG, PORTG, 0, portg, ping, ddrg),
        pg1: PG1 = (crate::pac::PORTG, PORTG, 1, portg, ping, ddrg),
        pg2: PG2 = (crate::pac::PORTG, PORTG, 2, portg, ping, ddrg),
        pg3: PG3 = (crate::pac::PORTG, PORTG, 3, portg, ping, ddrg),
        pg4: PG4 = (crate::pac::PORTG, PORTG, 4, portg, ping, ddrg),
        pg5: PG5 = (crate::pac::PORTG, PORTG, 5, portg, ping, ddrg),
    }
}
